machinemanagment/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'programmers', views.ProgrammerViewSet)

urlpatterns = [
    path('', include(router.urls))
]

machinemanagment/inventario/urls.py
from django.urls import path
from inventario import views

app_name = "inventario"

urlpatterns = [

# Urls para el inventario
    path('lista-inventario/', views.lista_inventarios.as_view(), name='lista_inventario'),
    path('detalle-inventario/<int:pk>/', views.DetalleInventario.as_view(), name='detalle_inventario'),

# Urls para piezas
    path('lista-piezas/', views.lista_piezas.as_view(), name='lista_piezas'),
    path('detalle-pieza/<int:pk>/', views.DetallePieza.as_view(), name='detalle_pieza'),
    path('actualizar-pieza/<int:pk>/', views.ActualizarPieza.as_view(), name='actualizar_pieza'),
    path('eliminar-pieza/<int:pk>/', views.EliminarPieza.as_view(), name='eliminar_pieza'),
    path('agregar-pieza/', views.AgregarPieza.as_view(), name='agregar_pieza'),

# Urls para añadir piezas
    path('add-pieza/', views.agregar_piezas.as_view(), name='add_pieza'),
    path('detalle-add-pieza/<int:pk>/', views.DetalleAddPieza.as_view(), name='detalle_add_pieza'),
    path('actualizar-add-pieza/<int:pk>/', views.ActualizarAddPieza.as_view(), name='actualizar_add_pieza'),
    path('eliminar-add-pieza/<int:pk>/', views.EliminarAddPieza.as_view(), name='eliminar_add_pieza'),
    path('agregar-add-pieza/', views.Agregar_stock_Pieza.as_view(), name='agregar_add_pieza'),

# Urls para proveedores
    path('lista-proveedor/', views.lista_proveedor.as_view(), name='lista_proveedor'),
    path('agregar-proveedor/', views.AgregarProveedor.as_view(), name='agregar_proveedor_pieza'),  # Agregar proveedor
    path('actualizar-proveedor/<int:pk>/', views.ActualizarProveedor.as_view(), name='actualizar_proveedor_pieza'),  # Modificar proveedor
    path('detalle-proveedor/<int:pk>/', views.DetalleProveedor.as_view(), name='detalle_proveedor_pieza'),  # Ver detalles
    path('eliminar-proveedor/<int:pk>/', views.EliminarProveedor.as_view(), name='eliminar_proveedor_pieza'),  # Eliminar proveedor
]

machinemanagment/machinemanagment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from rest_framework.documentation import include_docs_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('maquinaria/', include("maquinaria.urls")),
    path('empleados/', include("empleados.urls")),
    path('empresas/', include('empresa.urls')),
    path('inventario/', include("inventario.urls")),
    path('status/', include("status.urls")),
    path('administrador/', include("administrador.urls")),
    path('api/v1/', include('api.urls')),
    path('docs/', include_docs_urls(title= 'Api Documentation'))
    
]

machinemanagment/inventario/models.py
from django.db import models

class Piezas(models.Model):
    id_pieza = models.AutoField(primary_key=True)
    nombre_pieza = models.CharField(max_length=50, blank=True, null=True)
    precio = models.FloatField(blank=True, null=True)
    descripcion = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'piezas'

class InventarioPiezas(models.Model):
    id_inventario = models.AutoField(primary_key=True)
    cantidad_stock_piezas = models.IntegerField()
    id_pieza = models.ForeignKey('Piezas', models.DO_NOTHING, db_column='id_pieza')
    fecha_entrada = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'inventario_piezas'

class AddPieza(models.Model):
    id_add_pieza = models.AutoField(primary_key=True)
    id_pieza = models.ForeignKey('Piezas', models.DO_NOTHING, db_column='id_pieza', blank=True, null=True)
    id_proveedor = models.ForeignKey('ProveedorPiezas', models.DO_NOTHING, db_column='id_proveedor', blank=True, null=True)
    cantidad_piezas = models.IntegerField(blank=True, null=True)
    descripcion_pieza = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'add_pieza'

class ProveedorPiezas(models.Model):
    id_proveedor_piezas = models.AutoField(primary_key=True)
    nombre_empresa = models.CharField(db_column='Nombre_empresa', max_length=100, blank=True, null=True)  
    rfc = models.CharField(db_column='RFC', max_length=40, blank=True, null=True)
    fecha_registro = models.DateField(blank=True, null=True)
    tipo_moneda_pago = models.CharField(max_length=16)

    class Meta:
        managed = False
        db_table = 'proveedor_piezas'

machinemanagment/inventario/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Piezas, InventarioPiezas, ProveedorPiezas, AddPieza
from django.views import generic
from django.urls import reverse_lazy

#clases para el inventario
# Vista para la lista de inventario de piezas
class lista_inventarios(generic.ListView):
    model = InventarioPiezas
    template_name = "inventario/inventario/lista_inventario.html"
    context_object_name = "Inventario"
# Vista para el detalle del inventario
class DetalleInventario(generic.DetailView):
    model = InventarioPiezas
    template_name = "inventario/inventario/inventario_detalle.html"
    context_object_name = "inventario"
# Fin de clases para invnetario


#Clases para piezas
# Vista para la lista de piezas
class lista_piezas(generic.ListView):
    model = Piezas
    template_name = "inventario/Piezas/lista_piezas.html"
    context_object_name = "piezas"
# Vista para ver los detalles de una pieza
class DetallePieza(generic.DetailView):
    model = Piezas
    template_name = "inventario/Piezas/detalle_pieza.html"  # Asegúrate de tener este template
    context_object_name = "pieza"
# Vista para actualizar una pieza existente
class ActualizarPieza(generic.UpdateView):
    model = Piezas
    template_name = "inventario/Piezas/actualizar_pieza.html"  # Asegúrate de tener este template
    fields = ['nombre_pieza', 'precio', 'descripcion']
    success_url = reverse_lazy('inventario:lista_piezas')
# Vista para eliminar una pieza
class EliminarPieza(generic.DeleteView):
    model = Piezas
    template_name = "inventario/Piezas/eliminar_pieza.html"  # Asegúrate de tener este template
    context_object_name = "piezas"
    success_url = reverse_lazy('inventario:lista_piezas')
# Vista para agregar una nueva pieza
class AgregarPieza(generic.CreateView):
    model = Piezas
    template_name = "inventario/Piezas/agregar_pieza.html"  # Asegúrate de tener este template
    fields = ['nombre_pieza', 'precio', 'descripcion']
    success_url = reverse_lazy('inventario:lista_piezas')
#Fin de clases para Piezas


##Clases para añadir piezas
# Vista para lista añadir pieza
class agregar_piezas(generic.ListView):
    model = AddPieza
    template_name = "inventario/Add_P/lista_add_pieza.html"
    context_object_name = "add_piezas"
#Detalle de las piezas agregadas
class DetalleAddPieza(generic.DetailView):
    model = AddPieza
    template_name = 'inventario/Add_P/detalle_add_pieza.html'
    context_object_name = 'add_pieza'
#Eliminar pieza agregada
class EliminarAddPieza(generic.DeleteView):
    model = AddPieza
    template_name = 'inventario/Add_P/eliminar_add_pieza.html'
    context_object_name = 'add_pieza'
    success_url = reverse_lazy('inventario:add_pieza')
#Actualizar pieza agregada
class ActualizarAddPieza(generic.UpdateView):
    model = AddPieza
    template_name = "inventario/Add_P/actualizar_add_pieza.html"  # Asegúrate de tener este template
    fields = ['id_pieza', 'id_proveedor', 'cantidad_piezas', 'descripcion_pieza']  # Los campos que deseas permitir que se actualicen
    success_url = reverse_lazy('inventario:add_pieza')
#Agregar stock de piezas
class Agregar_stock_Pieza(generic.CreateView):
    model = AddPieza
    template_name = "inventario/Add_P/agregar_add_pieza.html"
    fields = ['id_pieza', 'id_proveedor', 'cantidad_piezas', 'descripcion_pieza']
    success_url = reverse_lazy('inventario:add_pieza')  # Redirige a la lista después de agregar
#Fin de clases para añadir piezas




#Clases para proveedores
# Vista para la lista de proveedores
class lista_proveedor(generic.ListView):
    model = ProveedorPiezas
    template_name = "inventario/Proveedor/lista_proveedor.html"
    context_object_name = "proveedores"
# Vista para agregar un nuevo proveedor
class AgregarProveedor(generic.CreateView):
    model = ProveedorPiezas
    template_name = "inventario/Proveedor/agregar_proveedor.html"
    fields = ['nombre_empresa', 'rfc', 'fecha_registro', 'tipo_moneda_pago']
    success_url = reverse_lazy('inventario:lista_proveedor')  # Redirigir a la lista de proveedores después de agregar
# Vista para actualizar un proveedor
class ActualizarProveedor(generic.UpdateView):
    model = ProveedorPiezas
    template_name = "inventario/Proveedor/actualizar_proveedor.html"
    fields = ['nombre_empresa', 'rfc', 'fecha_registro', 'tipo_moneda_pago']
    success_url = reverse_lazy('inventario:lista_proveedor')  # Redirigir a la lista de proveedores después de la actualización
# Vista para ver los detalles de un proveedor
class DetalleProveedor(generic.DetailView):
    model = ProveedorPiezas
    template_name = "inventario/Proveedor/detalle_proveedor.html"
    context_object_name = "proveedor"  # Este es el nombre con el que accederás al proveedor en el template
# Vista para eliminar un proveedor
class EliminarProveedor(generic.DeleteView):
    model = ProveedorPiezas
    template_name = "inventario/Proveedor/eliminar_proveedor.html"
    context_object_name = "proveedor"  # Este es el nombre con el que accederás al proveedor en el template
    success_url = reverse_lazy('inventario:lista_proveedor')  # Redirigir a la lista de proveedores después de eliminar
#Fin de clases para proveedores

machinemanagment/templates/inventario/Proveedor/actualizar_proveedor.html
{% extends 'base/base.html' %}

{% block title %}Actualizar proveedor{% endblock title %}

{% block content %}
<h2 class="my-4">Actualizar Proveedor</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-warning btn-lg">Actualizar</button>
    </form>
{% endblock content %}

machinemanagment/templates/inventario/Proveedor/agregar_proveedor.html
{% extends 'base/base.html' %}

{% block title %}Añadir proveedor de piezas{% endblock title %}

{% block content %}
<div class="container">
    <h2 class="my-4">Añadir proveedor de piezas</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success btn-lg">Añadir</button>
    </form>
</div>
{% endblock content %}

machinemanagment/templates/inventario/Proveedor/detalle_proveedor.html
{% extends "base/base.html" %}

{% block title %}Detalles de Proveedor{% endblock title %}

{% block content %}
<div class="container">
    <h2>Detalles de Proveedor</h2>
    <ul>
        <li>ID: {{ proveedor.id_proveedor_piezas }}</li>
        <li>Nombre de la Empresa: {{ proveedor.nombre_empresa }}</li>
        <li>RFC: {{ proveedor.rfc }}</li>
        <li>Fecha de Registro: {{ proveedor.fecha_registro }}</li>
        <li>Tipo de Moneda de Pago: {{ proveedor.tipo_moneda_pago }}</li>
    </ul>
    <a href="{% url 'inventario:lista_proveedor' %}" class="btn btn-secondary">Regresar a la lista</a>
</div>
{% endblock content %}

machinemanagment/templates/inventario/Proveedor/eliminar_proveedor.html
{% extends 'base/base.html' %}

{% block title %}Eliminar Proveedor{% endblock title %}

{% block content %}
<div class="container">
    <h2 class="my-4">Eliminar Proveedor</h2>
    <p>¿Está seguro de eliminar el registro del proveedor: {{ proveedor.nombre_empresa }}?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-warning btn-lg">Eliminar</button>
    </form>
</div>
{% endblock content %}

machinemanagment/templates/inventario/Proveedor/lista_proveedor.html
{% extends 'base/base.html' %}

{% block title %}Lista de Proveedores de Piezas{% endblock title %}

{% block content %}
<div class="container">
    <h2>Lista de Proveedores de Piezas</h2>
    <a href="{% url 'inventario:agregar_proveedor_pieza' %}" class="btn btn-dark mb-3">Agregar nuevo proveedor</a>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre Empresa</th>
                <th>RFC</th>
                <th>Fecha de Registro</th>
                <th>Tipo de Moneda de Pago</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for proveedor in proveedores %}
            <tr>
                <td>{{ proveedor.id_proveedor_piezas }}</td>
                <td>{{ proveedor.nombre_empresa }}</td>
                <td>{{ proveedor.rfc }}</td>
                <td>{{ proveedor.fecha_registro }}</td>
                <td>{{ proveedor.tipo_moneda_pago }}</td>
                <td>
                    <a href="{% url 'inventario:detalle_proveedor_pieza' proveedor.id_proveedor_piezas %}" class="btn btn-light">Detalles</a>
                    <a href="{% url 'inventario:actualizar_proveedor_pieza' proveedor.id_proveedor_piezas %}" class="btn btn-primary">Modificar</a>
                    <a href="{% url 'inventario:eliminar_proveedor_pieza' proveedor.id_proveedor_piezas %}" class="btn btn-danger" onclick="return confirm('¿Estás seguro de eliminar este proveedor?');">Eliminar</a>
                </td>
            </tr>
            {% empty %}
                <tr>
                    <td colspan="6">No hay proveedores registrados.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}