machinemanagment/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'programmers', views.ProgrammerViewSet)

urlpatterns = [
    path('', include(router.urls))
]

machinemanagment/machinemanagment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from rest_framework.documentation import include_docs_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('maquinaria/', include("maquinaria.urls")),
    path('empleados/', include("empleados.urls")),
    path('empresas/', include('empresa.urls')),
    path('inventario/', include("inventario.urls")),
    path('status/', include("status.urls")),
    path('administrador/', include("administrador.urls")),
    path('api/v1/', include('api.urls')),
    path('docs/', include_docs_urls(title= 'Api Documentation'))
    
]

machinemanagment/maquinaria/urls.py
from django.urls import path
from maquinaria import views

app_name = "maquinaria"

urlpatterns = [
    path('', views.MaquinariaView.as_view(), name="maquinaria"),
    path('list/', views.MaquinariaListView.as_view(), name="maquinaria_list"),
    path('<int:pk>/detalles/', views.MaquinariaDetailView.as_view(), name="ver_maquinaria"),
    path('<int:pk>/editar/', views.MaquinariaUpdateView.as_view(), name="actualizar_maquinaria"),
    path('<int:pk>/eliminar/', views.MaquinariaDeleteView.as_view(), name="eliminar_maquinaria"),

    path('tipo/crear/', views.CrearTipoMantenimiento.as_view(), name='crear_tipo_mantenimiento'),
    path('tipo/lista/', views.ListaTiposMantenimiento.as_view(), name='lista_tipomantenimiento'),
    path('crear/', views.CrearMantenimiento.as_view(), name='crear_mantenimiento'),
    path('lista/', views.ListaMantenimientos.as_view(), name='Lista_mantenimiento'),
    path('tipo/actualizar/<int:pk>/', views.ActualizarTipoMantenimiento.as_view(), name='actualizar_tipo_mantenimiento'),
    path('tipo/eliminar/<int:pk>/', views.EliminarTipoMantenimiento.as_view(), name='eliminar_tipo_mantenimiento'),
    path('actualizar/<int:pk>/', views.ActualizarMantenimiento.as_view(), name='actualizar_mantenimiento'),
    path('eliminar/<int:pk>/', views.EliminarMantenimiento.as_view(), name='eliminar_mantenimiento'),

    path('pieza/añadir/', views.AñadirPiezaMantenimiento.as_view(), name='añadir_pieza'),
    path('pieza/lista/', views.ListaPiezasMantenimiento.as_view(), name='lista_piezasmante'),
    path('piezas/editar/<int:pk>/', views.EditarPiezasMantenimiento.as_view(), name='editar_pieza'),
    path('piezas/eliminar/<int:pk>/', views.EliminarPiezasMantenimiento.as_view(), name='eliminar_piezas'),

    path('detalle/lista/', views.listaDetalles.as_view(), name='lista_detalleMante'),
]

machinemanagment/maquinaria/models.py
from django.db import models
from empresa.models import Empresas

class Maquinaria(models.Model):
    id_maquinaria = models.AutoField(primary_key=True)
    nombre_maquinaria = models.CharField(max_length=100, blank=True, null=True)
    modelo = models.CharField(max_length=100, blank=True, null=True)
    marca = models.CharField(max_length=50, blank=True, null=True)
    fecha_adquisicion = models.DateField(blank=True, null=True)
    estado = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'maquinaria'

class TipoMantenimiento(models.Model):
    id_tipo_mantenimiento = models.AutoField(primary_key=True)
    nombre_tipo_mantenimiento = models.CharField(max_length=100, blank=True, null=True)
    descripcion = models.CharField(max_length=100, blank=True, null=True)
    precio = models.FloatField(blank=True, null=True)
    fecha_servicio = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tipo_mantenimiento'

class DetallemaquinariaEmpresa(models.Model):
    id_detalle_maquinaria_empresa = models.AutoField(primary_key=True)
    id_empresa = models.ForeignKey(Empresas, models.DO_NOTHING, db_column='id_empresa', blank=True, null=True)
    id_maquinaria = models.ForeignKey('Maquinaria', models.DO_NOTHING, db_column='id_maquinaria', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'detallemaquinaria_empresa'


class Mantenimientos(models.Model):
    id_mantenimiento = models.AutoField(primary_key=True)
    id_empresa = models.ForeignKey(Empresas, models.DO_NOTHING, db_column='id_empresa', blank=True, null=True)
    id_maquinaria = models.ForeignKey('Maquinaria', models.DO_NOTHING, db_column='id_maquinaria', blank=True, null=True)
    id_tipo_mantenimiento = models.ForeignKey('TipoMantenimiento', models.DO_NOTHING, db_column='id_tipo_mantenimiento', blank=True, null=True)
    responsable_mantenimiento = models.ForeignKey('empleados.Empleados', models.DO_NOTHING, db_column='Responsable_mantenimiento', blank=True, null=True)
    fecha_programada = models.DateField(blank=True, null=True)
    fecha_realizacion = models.DateField(blank=True, null=True)
    descripcion = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mantenimientos'

class PiezasMantenimiento(models.Model):
    ind_pieza_mantenimiento = models.AutoField(primary_key=True)
    id_mantenimiento = models.ForeignKey('Mantenimientos', models.DO_NOTHING, db_column='id_mantenimiento', blank=True, null=True)
    id_pieza = models.ForeignKey('inventario.Piezas', models.DO_NOTHING, db_column='id_pieza', blank=True, null=True)
    cantidad_usada = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'piezas_mantenimiento'

machinemanagment/maquinaria/forms.py
from django.forms import ModelForm
from .models import Maquinaria, Mantenimientos, TipoMantenimiento, PiezasMantenimiento


class MaquinariaForm(ModelForm):
    class Meta:
        model = Maquinaria
        fields = ['nombre_maquinaria', 'modelo', 'estado', 'fecha_adquisicion']

class MantenimientoForm(ModelForm):
    class Meta:
        model = Mantenimientos
        fields = ('id_empresa', 'id_maquinaria', 'id_tipo_mantenimiento', 'responsable_mantenimiento', 'fecha_programada', 'fecha_realizacion', 'descripcion')

class TipoMantenimientoForm(ModelForm):
    class Meta:
        model = TipoMantenimiento
        fields = ('nombre_tipo_mantenimiento', 'descripcion', 'precio', 'fecha_servicio')
    
class PiezasMantenimientoForm(ModelForm):
    class Meta:
        model = PiezasMantenimiento
        fields = ['id_mantenimiento', 'id_pieza', 'cantidad_usada']

machinemanagment/maquinaria/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .forms import MaquinariaForm, MantenimientoForm, TipoMantenimientoForm, PiezasMantenimientoForm
from .models import Maquinaria, Mantenimientos, TipoMantenimiento, PiezasMantenimiento, DetallemaquinariaEmpresa
from django.urls import reverse_lazy
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin


class MaquinariaView(generic.View):
    template_name = "maquinaria/maquinaria.html"
    
    def get(self, request):
        form = MaquinariaForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = MaquinariaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('maquinaria:maquinaria')  # Redirige a la misma vista o a otra que desees
        else:
            print(form.errors)  # Imprime los errores si el formulario no es válido
        return render(request, self.template_name, {'form': form})

class MaquinariaListView(generic.ListView):
    model = Maquinaria
    template_name = "maquinaria/maquinaria_list.html"
    context_object_name = "maquinarias"

class MaquinariaDetailView(generic.DetailView):
    model = Maquinaria
    template_name = "maquinaria/maquinaria_detail.html"
    context_object_name = "maquinaria"

class MaquinariaUpdateView(generic.UpdateView):
    model = Maquinaria
    form_class = MaquinariaForm
    template_name = "maquinaria/maquinaria_form.html"

    def get_success_url(self):
        return reverse_lazy('maquinaria:maquinaria_list')

class MaquinariaDeleteView(generic.DeleteView):
    model = Maquinaria
    template_name = "maquinaria/maquinaria_confirm_delete.html"
    success_url = reverse_lazy('maquinaria:maquinaria_list')


class CrearTipoMantenimiento(generic.CreateView):
    model = TipoMantenimiento
    form_class = TipoMantenimientoForm
    template_name = 'maquinaria/crear_tipo_mantenimiento.html'
    success_url = reverse_lazy("maquinaria:lista_tipomantenimiento")
    login_url = "home:index"

class ListaTiposMantenimiento(LoginRequiredMixin, generic.ListView):
    model = TipoMantenimiento
    template_name = 'maquinaria/lista_tipomantenimiento.html'
    login_url = "home:index"

class CrearMantenimiento(LoginRequiredMixin, generic.CreateView):
    model = Mantenimientos
    form_class = MantenimientoForm
    template_name = 'maquinaria/crear_mantenimiento.html'
    success_url = reverse_lazy('maquinaria:Lista_mantenimiento')
    login_url = "home:index"

class ListaMantenimientos(LoginRequiredMixin, generic.ListView):
    model = Mantenimientos
    template_name = 'maquinaria/Lista_mantenimiento.html'
    login_url = "home:index"

class ActualizarTipoMantenimiento(LoginRequiredMixin, generic.UpdateView):
    model = TipoMantenimiento
    form_class = TipoMantenimientoForm
    template_name = 'maquinaria/actualizar_tipo_mantenimiento.html'
    success_url = reverse_lazy('maquinaria:lista_tipomantenimiento')
    login_url = "home:index"

class EliminarTipoMantenimiento(LoginRequiredMixin, generic.DeleteView):
    model = TipoMantenimiento
    template_name = 'maquinaria/eliminar_tipo_mantenimiento.html'
    success_url = reverse_lazy('maquinaria:lista_tipomantenimiento')
    login_url = "home:index"


class ActualizarMantenimiento(LoginRequiredMixin, generic.UpdateView):
    model = Mantenimientos
    form_class = MantenimientoForm
    template_name = 'maquinaria/actualizar_mantenimiento.html'
    success_url = reverse_lazy('maquinaria:Lista_mantenimiento')
    login_url = "home:index"

class EliminarMantenimiento(LoginRequiredMixin, generic.DeleteView):
    model = Mantenimientos
    template_name = 'maquinaria/eliminar_mantenimiento.html'
    success_url = reverse_lazy('maquinaria:Lista_mantenimiento')
    login_url = "home:index"


class AñadirPiezaMantenimiento(generic.CreateView):
    model = PiezasMantenimiento
    form_class = PiezasMantenimientoForm
    template_name = 'maquinaria/añadir_pieza.html'
    success_url = reverse_lazy("maquinaria:lista_piezasmante")
    login_url = "home:index"

class ListaPiezasMantenimiento(LoginRequiredMixin, generic.ListView):
    model = PiezasMantenimiento
    template_name = 'maquinaria/lista_piezasmante.html'
    login_url = "home:index"

class EditarPiezasMantenimiento(LoginRequiredMixin, generic.UpdateView):
    model = Mantenimientos
    form_class = MantenimientoForm
    template_name = 'maquinaria/editar_pieza.html'
    success_url = reverse_lazy('maquinaria:lista_piezasmante')
    login_url = "home:index"

class EliminarPiezasMantenimiento(LoginRequiredMixin, generic.DeleteView):
    model = Mantenimientos
    template_name = 'maquinaria/eliminar_piezas.html'
    success_url = reverse_lazy('maquinaria:lista_piezasmante')
    login_url = "home:index"

class listaDetalles(LoginRequiredMixin, generic.ListView):
    model = DetallemaquinariaEmpresa
    template_name = 'maquinaria/lista_detalleMante.html'
    login_url = "home:index"

machinemanagment/templates/maquinaria/Lista_mantenimiento.html
{% extends 'base/base.html' %}

{% block title %}Lista de Mantenimientos{% endblock title %}

{% block content %}
<h2 class="my-4">Lista de Mantenimientos</h2>

    <form action="{% url 'maquinaria:crear_mantenimiento' %}">
        <button type="submit" class="btn btn-outline-success mb-3">Agregar Mantenimiento</button>
    </form>

    {% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Empresa</th>
                <th>Maquinaria</th>
                <th>Tipo de Mantenimiento</th>
                <th>Responsable</th>
                <th>Fecha Programada</th>
                <th>Fecha Realización</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for Mantenimiento in object_list %}
                <tr>
                    <td>{{ Mantenimiento.id_empresa }}</td>   <!--.nombre_empresa-->
                    <td>{{ Mantenimiento.id_maquinaria }}</td>   <!--.nombre_maquinaria-->
                    <td>{{ Mantenimiento.id_tipo_mantenimiento.nombre_tipo_mantenimiento }}</td>
                    <td>{{ Mantenimiento.responsable_mantenimiento }}</td> <!--.nombre_empleado-->
                    <td>{{ Mantenimiento.fecha_programada }}</td>
                    <td>{{ Mantenimiento.fecha_realizacion }}</td>
                    <td>{{ Mantenimiento.descripcion }}</td>
                    <td>
                        <a href="{% url 'maquinaria:actualizar_mantenimiento' Mantenimiento.pk %}" class="btn btn-outline-warning btn-sm mb-3">Actualizar</a>
                        <a href="{% url 'maquinaria:eliminar_mantenimiento' Mantenimiento.pk %}" class="btn btn-outline-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No se encontraron mantenimientos.</p>
{% endif %}
{% endblock content %}

machinemanagment/templates/maquinaria/actualizar_mantenimiento.html
{% extends 'base/base.html' %}

{% block title %}Actualizar Mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Actualizar Mantenimiento</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-warning btn-lg">Actualizar</button>
    </form>
{% endblock content %}

machinemanagment/templates/maquinaria/actualizar_tipo_mantenimiento.html
{% extends 'base/base.html' %}

{% block title %}Actualizar Tipo de Mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Actualizar Tipo Mantenimiento</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-warning btn-lg">Actualizar</button>
    </form>
{% endblock content %}

machinemanagment/templates/maquinaria/añadir_pieza.html
{% extends 'base/base.html' %}

{% block title %}Añadir piezas mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Añadir piezas mantenimiento</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success btn-lg">Añadir</button>
    </form>
{% endblock content %}

machinemanagment/templates/maquinaria/crear_mantenimiento.html
{% extends 'base/base.html' %}

{% block title %}Crear Mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Crear Mantenimiento</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success btn-lg">Crear</button>
    </form>
{% endblock content %}

machinemanagment/templates/maquinaria/crear_tipo_mantenimiento.html
{% extends 'base/base.html' %}

{% block title %}Crear Tipo de Mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Crear Tipo Mantenimiento</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success btn-lg">Crear</button>
    </form>
{% endblock content %}

machinemanagment/templates/maquinaria/editar_pieza.html
{% extends 'base/base.html' %}

{% block title %}Editar pieza mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Editar pieza mantenimiento</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-warning btn-lg">Aceptar</button>
    </form>
{% endblock content %}

machinemanagment/templates/maquinaria/eliminar_mantenimiento.html
{% extends 'base/base.html' %}

{% block title %}Eliminar Mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Eliminar Mantenimiento</h2>
    <p>¿Está seguro de eliminar el mantenimiento {{ object.id_mantenimiento }}?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-warning btn-lg">Eliminar</button>
    </form>
{% endblock content %}

machinemanagment/templates/maquinaria/eliminar_piezas.html
{% extends 'base/base.html' %}

{% block title %}Eliminar piezas mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Eliminar piezas de mantenimiento</h2>
    <p>¿Está seguro de eliminar el registro? {{ object.ind_pieza_mantenimiento }}?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-warning btn-lg">Eliminar</button>
    </form>
{% endblock content %}

machinemanagment/templates/maquinaria/lista_piezasmante.html
{% extends 'base/base.html' %}

{% block title %}Lista de Piezas mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Lista de Piezas mantenimiento</h2>

    <form action="{% url 'maquinaria:añadir_pieza' %}">
        <button type="submit" class="btn btn-outline-success mb-3">Añadir piezas</button>
    </form>

    {% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Mantenimiento</th>
                <th>ID pieza</th>
                <th>Cantidad uso</th>              
            </tr>
        </thead>
        <tbody>
            {% for piezas in object_list %}
                <tr>
                    <td>{{ piezas.id_mantenimiento }}</td>   <!--.nombre_empresa-->
                    <td>{{ piezas.id_pieza.nombre_pieza }}</td>   <!--.nombre_maquinaria-->
                    <td>{{ piezas.cantidad_usada }}</td>
                    <td>
                        <a href="{% url 'maquinaria:editar_pieza' piezas.pk %}" class="btn btn-outline-warning btn-sm mb-3">Editar</a>
                        <a href="{% url 'maquinaria:eliminar_piezas' piezas.pk %}" class="btn btn-outline-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No se encontraron piezas.</p>
{% endif %}
{% endblock content %}

machinemanagment/templates/maquinaria/lista_tipomantenimiento.html
{% extends 'base/base.html' %}

{% block title %}Lista de Tipos de Mantenimiento{% endblock title %}

{% block content %}
<h2 class="my-4">Lista Tipo de Mantenimientos</h2>
    <form action="{% url 'maquinaria:crear_tipo_mantenimiento' %}">
        <button type="submit" class="btn btn-outline-primary mt-3 mb-3">Agregar Tipo de Mantenimiento</button>
    </form>
    
    {% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Precio</th>
                <th>Fecha de Servicio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for tipo_mantenimiento in object_list %}
                <tr>
                    <td>{{ tipo_mantenimiento.nombre_tipo_mantenimiento }}</td>
                    <td>{{ tipo_mantenimiento.descripcion }}</td>
                    <td>{{ tipo_mantenimiento.precio }}</td>
                    <td>{{ tipo_mantenimiento.fecha_servicio }}</td>
                    <td>
                        <a href="{% url 'maquinaria:actualizar_tipo_mantenimiento' tipo_mantenimiento.pk %}" class="btn btn-outline-warning btn-sm">Actualizar</a>
                        <a href="{% url 'maquinaria:eliminar_tipo_mantenimiento' tipo_mantenimiento.pk %}" class="btn btn-outline-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No se encontraron tipos de mantenimiento.</p>
{% endif %}
{% endblock content %}

machinemanagment/templates/maquinaria/maquinaria.html
{% extends "base/base.html" %}

{% block title %}Maquinaria{% endblock title %}


{% block content %}
<div class="container">
    <h2>Agregar maquinaria</h2>
    {{error}}
    <form action = "" method ="POST">
        {% csrf_token %}
        {{form}}
        <button>Save</button>
    </form>

</div>
{% endblock content  %}

machinemanagment/templates/maquinaria/maquinaria_detail.html
{% extends "base/base.html" %}

{% block title %}Detalles de Maquinaria{% endblock title %}

{% block content %}
<div class="container">
    <h2>Detalles de Maquinaria</h2>
    <ul>
        <li>ID: {{ maquinaria.id_maquinaria }}</li>
        <li>Nombre: {{ maquinaria.nombre_maquinaria }}</li>
        <li>Modelo: {{ maquinaria.modelo }}</li>
        <li>Marca: {{ maquinaria.marca }}</li>
        <li>Fecha de Adquisición: {{ maquinaria.fecha_adquisicion }}</li>
        <li>Estado: {{ maquinaria.estado }}</li>
    </ul>
    <a href="{% url 'maquinaria:maquinaria_list' %}" class="btn btn-secondary">Regresar a la lista</a>
</div>
{% endblock content %}

machinemanagment/templates/maquinaria/maquinaria_form.html
{% extends "base/base.html" %}

{% block title %}Actualizar Maquinaria{% endblock title %}

{% block content %}
<div class="container">
    <h2>Actualizar Maquinaria</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
        <a href="{% url 'maquinaria:maquinaria_list' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock content %}