machinemanagment/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'programmers', views.ProgrammerViewSet)

urlpatterns = [
    path('', include(router.urls))
]

machinemanagment/empleados/urls.py
from django.urls import path

from empleados import views

app_name = "empleados"

urlpatterns = [
  path('', views.EmpleadosView.as_view(), name="empleados"),
    path('list/', views.EmpleadosListView.as_view(), name="empleado_list"),
    path('<int:pk>/detalles/', views.EmpleadosDetailView.as_view(), name="ver_empleado"),
    path('<int:pk>/editar/', views.EmpleadosUpdateView.as_view(), name="actualizar_empleado"),
    path('<int:pk>/eliminar/', views.EmpleadosDeleteView.as_view(), name="eliminar_empleado"),
]

machinemanagment/empresa/urls.py
from django.urls import path
from . import views
from .views import lista_empresas, crear_empresa, actualizar_empresa, eliminar_empresa

app_name = 'empresa'

urlpatterns = [
    path('', lista_empresas, name='lista_empresas'),  
    path('crear/', crear_empresa, name='crear_empresa'),
    path('actualizar/<int:pk>/', actualizar_empresa, name='actualizar_empresa'),
    path('eliminar/<int:pk>/', eliminar_empresa, name='eliminar_empresa'),
    path('detalle/<int:pk>/', views.empresa_detalle, name='detalle_empresa'),
]

machinemanagment/inventario/urls.py
from django.urls import path
from inventario import views

app_name = "inventario"

urlpatterns = [

# Urls para el inventario
    path('lista-inventario/', views.lista_inventarios.as_view(), name='lista_inventario'),
    path('detalle-inventario/<int:pk>/', views.DetalleInventario.as_view(), name='detalle_inventario'),

# Urls para piezas
    path('lista-piezas/', views.lista_piezas.as_view(), name='lista_piezas'),
    path('detalle-pieza/<int:pk>/', views.DetallePieza.as_view(), name='detalle_pieza'),
    path('actualizar-pieza/<int:pk>/', views.ActualizarPieza.as_view(), name='actualizar_pieza'),
    path('eliminar-pieza/<int:pk>/', views.EliminarPieza.as_view(), name='eliminar_pieza'),
    path('agregar-pieza/', views.AgregarPieza.as_view(), name='agregar_pieza'),

# Urls para añadir piezas
    path('add-pieza/', views.agregar_piezas.as_view(), name='add_pieza'),
    path('detalle-add-pieza/<int:pk>/', views.DetalleAddPieza.as_view(), name='detalle_add_pieza'),
    path('actualizar-add-pieza/<int:pk>/', views.ActualizarAddPieza.as_view(), name='actualizar_add_pieza'),
    path('eliminar-add-pieza/<int:pk>/', views.EliminarAddPieza.as_view(), name='eliminar_add_pieza'),
    path('agregar-add-pieza/', views.Agregar_stock_Pieza.as_view(), name='agregar_add_pieza'),

# Urls para proveedores
    path('lista-proveedor/', views.lista_proveedor.as_view(), name='lista_proveedor'),
    path('agregar-proveedor/', views.AgregarProveedor.as_view(), name='agregar_proveedor_pieza'),  # Agregar proveedor
    path('actualizar-proveedor/<int:pk>/', views.ActualizarProveedor.as_view(), name='actualizar_proveedor_pieza'),  # Modificar proveedor
    path('detalle-proveedor/<int:pk>/', views.DetalleProveedor.as_view(), name='detalle_proveedor_pieza'),  # Ver detalles
    path('eliminar-proveedor/<int:pk>/', views.EliminarProveedor.as_view(), name='eliminar_proveedor_pieza'),  # Eliminar proveedor
]

machinemanagment/machinemanagment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from rest_framework.documentation import include_docs_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('maquinaria/', include("maquinaria.urls")),
    path('empleados/', include("empleados.urls")),
    path('empresas/', include('empresa.urls')),
    path('inventario/', include("inventario.urls")),
    path('status/', include("status.urls")),
    path('administrador/', include("administrador.urls")),
    path('api/v1/', include('api.urls')),
    path('docs/', include_docs_urls(title= 'Api Documentation'))
    
]

machinemanagment/status/urls.py
from django.urls import path, include
from .views import CreateStatus, ListStatus, DetailStatus, UpdateStatus, DeleteStatus, graficas_view, BancoView, BancoListView, BancoDetailView, BancoUpdateView, BancoDeleteView, ReparacionesView, ReparacionesListView, ReparacionesDetailView, ReparacionesUpdateView, ReparacionesDeleteView, HistorialMaquinasView, HistorialMaquinasListView, HistorialMaquinasDetailView, HistorialMaquinasUpdateView, HistorialMaquinasDeleteView


app_name = 'status'




urlpatterns = [
    
    path('status/create/', CreateStatus.as_view(), name='status_create'),
    path('status/', ListStatus.as_view(), name='status_list'),
    path('status/graficas/', graficas_view, name='status_graficas'),  # Nueva ruta para las gráficas
    path('status/<int:pk>/', DetailStatus.as_view(), name='status_detail'),
    path('status/update/<int:pk>/', UpdateStatus.as_view(), name='status_update'),
    path('status/delete/<int:pk>/', DeleteStatus.as_view(), name='status_delete'),

    path('', BancoView.as_view(), name='banco'),
    path('list/', BancoListView.as_view(), name='bancoem_list'),
    path('<int:pk>/detalles/', BancoDetailView.as_view(), name='ver_banco'),
    path('<int:pk>/editar/', BancoUpdateView.as_view(), name='actualizar_banco'),
    path('<int:pk>/eliminar/', BancoDeleteView.as_view(), name='eliminar_banco'),

    path('reparaciones/create/', ReparacionesView.as_view(), name='reparaciones'),
    path('reparaciones/lista/', ReparacionesListView.as_view(), name='reparaciones_list'),
    path('reparaciones/detalles/<int:pk>/', ReparacionesDetailView.as_view(), name='ver_reparaciones'),
    path('reparaciones/editar/<int:pk>/', ReparacionesUpdateView.as_view(), name='actualizar_reparaciones'),
    path('reparaciones/eliminar<int:pk>/', ReparacionesDeleteView.as_view(), name='eliminar_reparaciones'),

    path('HistorialMaquinas/create/', HistorialMaquinasView.as_view(), name='historial_maquinas'),
    path('HistorialMaquinas/lista/', HistorialMaquinasListView.as_view(), name='historial_maquinas_list'),
    path('HistorialMaquinas/detalles/<int:pk>/', HistorialMaquinasDetailView.as_view(), name='ver_historial'),
    path('HistorialMaquinas/editar/<int:pk>/', HistorialMaquinasUpdateView.as_view(), name='actualizar_historial'),
    path('HistorialMaquinas/eliminar<int:pk>/', HistorialMaquinasDeleteView.as_view(), name='eliminar_historial'),
]

machinemanagment/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
  </head>
  <body>
    <div class="row">
      {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">MachineManagment</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'status:status_graficas' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'empresa:lista_empresas' %}">Empresa</a>
                  </li>

                  <!-- Menú desplegable para Mantenimiento -->
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Maquinaria
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'maquinaria:maquinaria_list' %}">Maquinaria</a></li>
                    <li><a class="dropdown-item" href="{% url 'maquinaria:lista_tipomantenimiento' %}">Tipos de Mantenimiento</a></li>
                    <li><a class="dropdown-item" href="{% url 'maquinaria:Lista_mantenimiento' %}">Mantenimientos</a></li>
                    <li><a class="dropdown-item" href="{% url 'maquinaria:lista_piezasmante' %}"> Piezas Mantenimiento</a></li>
                    <li><a class="dropdown-item" href="{% url 'maquinaria:lista_detalleMante' %}"> Detalles Mantenimiento</a></li>
                  </ul>
                </li>

                          <!-- Menú desplegable para Mantenimiento -->
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Inventario
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'inventario:lista_inventario' %}">Inventario Piezas</a></li>
                    <li><a class="dropdown-item" href="{% url 'inventario:lista_piezas' %}">Piezas</a></li>
                    <li><a class="dropdown-item" href="{% url 'inventario:add_pieza' %}">Añadir Piezas</a></li>
                    <li><a class="dropdown-item" href="{% url 'inventario:lista_proveedor' %}">Proveedor Piezas</a></li>
                  </ul>
                </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'empleados:empleado_list' %}">Empleados</a>
                  </li>
                          <!-- Menú desplegable para Mantenimiento -->
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Estatus
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'status:status_graficas' %}">Graficas</a></li>
                    <li><a class="dropdown-item" href="{% url 'status:status_list' %}"> Lista Estatus</a></li>
                    <li><a class="dropdown-item" href="{% url 'status:bancoem_list' %}">Banco</a></li>
                    <li><a class="dropdown-item" href="{% url 'status:reparaciones_list' %}">Reparaciones</a></li>
                    <li><a class="dropdown-item" href="{% url 'status:historial_maquinas_list' %}">HistorialMaquinas</a></li>


                  </ul>
                </li>


                          <!-- Menú desplegable para Mantenimiento -->
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Administrador
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'administrador:Areas' %}">Areas</a></li>
                  </ul>
                </li>

                  
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
        </nav>
      {% endif %}
    </div>

    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          {% block content %}
          {% endblock content %}
        </div>
        <div class="col-2"></div>
    </div>
    
    <!-- Footer (opcional, si lo necesitas) -->
    <footer class="text-center mt-4">
      <p>&copy; 2024 MachineManagement</p>
    </footer>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>